# Generated by Django 4.0.1 on 2022-01-10 18:52

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_listing_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default_currency='USD', max_digits=14),
        ),
    ]
