# Generated by Django 4.0.1 on 2022-01-10 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_listing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='addDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
