# Generated by Django 4.0.1 on 2022-01-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_listing_adddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='neighborhood',
            field=models.CharField(choices=[('Lower East Side', 'Lower East Side'), ('Financial District', 'Financial District'), ('Chelsea', 'Chelsea'), ('West Village', 'West Village'), ('East Village', 'East Village'), ('SoHo', 'SoHo'), ('Tribeca', 'Tirbeca'), ("Hell's Kitchen", "Hell's Kitchen"), ('Midtown', 'Midtown'), ('Upper West Side', 'Upper West Side'), ('Flatiron', 'Flatiron')], max_length=300),
        ),
    ]
