# Generated by Django 4.0.1 on 2022-01-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='averageRating',
            field=models.FloatField(default=0),
        ),
    ]
