# Generated by Django 4.0.1 on 2022-01-12 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='averageRating',
        ),
    ]
