# Generated by Django 4.0.1 on 2022-01-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_listing_averagerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating_layout',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_location',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_price',
            field=models.FloatField(default=0),
        ),
    ]
