# Generated by Django 4.0.1 on 2022-01-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_review_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
